namespace TSQL
{
    public enum TokenType
    {
        NONE,
        IDENTIFIER,
        VARIABLE,
        STRING, WHOLE_NUMBER, DECIMAL,
        PLUS, MINUS, SLASH, STAR, MODULO,
        SEMICOLON, COMMA, DOT,
        LEFT_PAREN, RIGHT_PAREN,
        EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, NOT_EQUAL,
        NOT_LESS, NOT_GREATER, BITWISE_NOT,
        WHITESPACE, COMMENT,
        EOF,
        // Keywords - This comment is used by a source generator to mark the keywords section, do not delete it.
        ADD, ALL, ALTER, AND, ANY, AS, ASC, AUTHORIZATION,
        BACKUP, BEGIN, BETWEEN, BREAK, BROWSE, BULK, BY,
        CASCADE, CASE, CAST, CHECK, CHECKPOINT, CLOSE, CLUSTERED, COALESCE, COLLATE, COLUMN, COMMIT, COMPUTE,
        CONSTRAINT, CONTAINS, CONTAINSTABLE, CONTINUE, CONVERT, CREATE, CROSS, CURRENT, CURRENT_DATE,
        CURRENT_TIME, CURRENT_TIMESTAMP, CURRENT_USER, CURSOR,
        DATABASE, DBCC, DEALLOCATE, DECLARE, DEFAULT, DELETE, DENY, DESC, DISK, DISTINCT, DISTRIBUTED,
        DOUBLE, DROP, DUMP,
        ELSE, END, ERRLVL, ESCAPE, EXCEPT, EXEC, EXECUTE, EXISTS, EXIT, EXTERNAL,
        FETCH, FILE, FILLFACTOR, FOR, FOREIGN, FREETEXT, FREETEXTTABLE, FROM, FULL, FUNCTION,
        GOTO, GRANT, GROUP,
        HAVING, HOLDLOCK,
        IDENTITY, IDENTITY_INSERT, IDENTITYCOL, IF, IN, INDEX, INNER, INSERT, INTERSECT, INTO, IS,
        JOIN,
        KEY, KILL,
        LEFT, LIKE, LINENO, LOAD,
        MERGE,
        NATIONAL, NOCHECK, NONCLUSTERED, NOT, NULL, NULLIF,
        OF, OFF, OFFSETS, ON, OPEN, OPENDATASOURCE, OPENQUERY, OPENROWSET, OPENXML, OPTION, OR, ORDER, OUTER, OVER,
        PERCENT, PIVOT, PLAN, PRECISION, PRIMARY, PRINT, PROC, PROCEDURE, PUBLIC,
        RAISERROR, READ, READTEXT, RECONFIGURE, REFERENCES, REPLICATION, RESTORE, RESTRICT,
        RETURN, REVERT, REVOKE, RIGHT, ROLLBACK, ROWCOUNT, ROWGUIDCOL, RULE,
        SAVE, SCHEMA, SECURITYAUDIT, SELECT,
        SEMANTICKEYPHRASETABLE, SEMANTICSIMILARITYDETAILSTABLE, SEMANTICSIMILARITYTABLE,
        SESSION_USER, SET, SETUSER, SHUTDOWN, SOME, STATISTICS, SYSTEM_USER,
        TABLE, TABLESAMPLE, TEXTSIZE, THEN, TO, TOP, TRAN, TRANSACTION, TRIGGER, TRUNCATE, TRY_CAST, TRY_CONVERT, TSEQUAL,
        UNION, UNIQUE, UNPIVOT, UPDATE, UPDATETEXT, USE, USER,
        VALUES, VARYING, VIEW,
        WAITFOR, WHEN, WHERE, WHILE, WITH, WITHIN /*WITHIN = WITHIN GROUP*/, WRITETEXT,

        // Window function keywords (contextual - can also be used as identifiers)
        PARTITION, ROWS, RANGE, UNBOUNDED, PRECEDING, FOLLOWING, ROW,

        // Ranking functions (contextual - can also be used as identifiers)
        ROW_NUMBER, RANK, DENSE_RANK, NTILE,

        // FROM clause keywords (contextual - can also be used as identifiers)
        APPLY, LOOP, HASH, REMOTE, SYSTEM, CONTAINED, REPEATABLE,

        // GROUP BY keywords (contextual - can also be used as identifiers)
        ROLLUP, CUBE, GROUPING, SETS
    }
}
