<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>1.2.0</Version>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\TSQL.snk</AssemblyOriginatorKeyFile>
    <IncludeSymbols>True</IncludeSymbols>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>TSQL Parser Standard Library</Title>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TSQL\TSQL.csproj" />
  </ItemGroup>

</Project>
